<a href="https://colab.research.google.com/github/divyaaarumugam5-design/data_prep-features_assignment/blob/main/DataPrep_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import pandas as pd

data = {
    'Gender': ['Male', 'Female', 'Female', 'Male', 'Female'],
    'City': ['Mumbai', 'Delhi', 'Chennai', 'Mumbai', 'Delhi'],
    'Size': ['Small', 'Large', 'Medium', 'Large', 'Small'],
    'Age': [25, 45, 32, 60, 28],
    'Fare': [15, 300, 85, 450, 20]
}

df = pd.DataFrame(data)
print(df)

   Gender     City    Size  Age  Fare
0    Male   Mumbai   Small   25    15
1  Female    Delhi   Large   45   300
2  Female  Chennai  Medium   32    85
3    Male   Mumbai   Large   60   450
4  Female    Delhi   Small   28    20

Task 1 — Categorical Encoding
Apply the correct encoding method to each categorical column:

Gender → Label Encoding
City → One-Hot Encoding (drop one column to avoid the dummy variable trap)
Size → Label Encoding with the correct order: Small=0, Medium=1, Large=2

In [9]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

df["Gender"]=le.fit_transform(df["Gender"])
df=pd.get_dummies(df,columns=["City"],drop_first=True)
size_ord={"Small":0,"Medium":1,"Large":2}
df["Size"]=df["Size"].map(size_ord)

In [10]:
#Printing df after encoding
df

   Gender  Size  Age  Fare  City_Delhi  City_Mumbai
0       1     0   25    15       False         True
1       0     2   45   300        True        False
2       0     1   32    85       False        False
3       1     2   60   450       False         True
4       0     0   28    20        True        False

Task 2 — Feature Scaling
The Fare column contains a value of 450 which is a potential outlier. Apply the appropriate scaler to both Age and Fare, and briefly justify your choice in a comment.

In [11]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import RobustScaler
scaler=StandardScaler()
rob_scale=RobustScaler()
df["Age"]=scaler.fit_transform(df[["Age"]])
df["Fare"]=rob_scale.fit_transform(df[["Fare"]])

Age and Fare are two numerical values, since Age is around25 to 60 and Fare field is around 450 is a potential outlier. Standard Scaler calulated by mean and Standard deviation here 450 is outlier will affect results - So for Fare we need to use  Robust scaler which we is calcualted by median and IQR not affected by outlier so it is good to handle the outliers!

In [12]:
#printing df after scaling

df

   Gender  Size       Age      Fare  City_Delhi  City_Mumbai
0       1     0 -1.004168 -0.250000       False         True
1       0     2  0.540706  0.767857        True        False
2       0     1 -0.463462  0.000000       False        False
3       1     2  1.699361  1.303571       False         True
4       0     0 -0.772437 -0.232143        True        False